---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: labels-pipeline
spec:
  tasks:
  - name: mytask1
    params:
    - name: PR
      value: $(context.pipelineRun.name)
    taskSpec:
      params:
      - name: PR
      steps:
      - name: hello
        image: quay.io/openshift-pipeline/ci
        script: |
          #!/usr/bin/env bash
          echo "Hello from task 1"
          oc label pipelinerun $(params.PR) foo=bar
          sleep $[ $RANDOM % 10 + 10 ]
---
piVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: pac-labels-pipeline-
spec:
  pipelineRef:
    name: labels-pipeline
  timeout: 3m
